### ISSUE TITLE
Can I replace "create_graph=True" by "retain_graph=True" when compute gradients with meta_trian_loss?

### ISSUE THREAD

**Issue by Abner228** [Pulkit-Khandelwal/medical-mldg-seg#2]
if set create_graph=True, graphics ram increased rapidly. 
I get 32GB  graphics ram, but it is far from enough to run the Unet3D, may I ask how many graphics ram did you use when the patch size equal 96X96X96?

**Comment by Pulkit-Khandelwal** [comment]
I used 64x64x64 on 24GB card. Try to use smaller batch size and smaller patches.

Also, hope this helps from PyTorch documentation:

retain_graph – If False, the graph used to compute the grads will be freed. Note that in nearly all cases setting this option to True is not needed and often can be worked around in a much more efficient way. Defaults to the value of create_graph.

create_graph – If True, graph of the derivative will be constructed, allowing to compute higher order derivative products. Defaults to False.

**Comment by Abner228** [comment]
I'm not sure if this is right:
if set create_graph=True, the second order derivative will be constructed
if set retain_graph=True, create_graph=Flase, I am doing first-order approximation of MAML.

**Comment by Pulkit-Khandelwal** [comment]
Yes, exactly! So, we will need the create_graph=True so that the second order derivatives are computed.

**Comment by Abner228** [comment]
Thanks for your reply. Regards.
